# Generated by Django 2.2.12 on 2020-05-01 02:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=15)),
                ('Money_Need', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('Subject', models.TextField(max_length=100)),
                ('Description', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=15)),
                ('Money', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loans_Money', models.PositiveIntegerField()),
                ('Loans_Date', models.DateTimeField(auto_now_add=True)),
                ('Loans_Borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Borrow')),
                ('Loans_Lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Lender')),
            ],
        ),
        migrations.AddField(
            model_name='borrow',
            name='Transactions',
            field=models.ManyToManyField(through='loans.Loans', to='loans.Lender'),
        ),
    ]
